#!/usr/bin/env bash
NOTES_DIR="$HOME/syncthing/notes/University"
CLASSES=$(find $NOTES_DIR -mindepth 3 -maxdepth 3 -type d | awk -F/ '{print $NF "\t" $0}')
CLASS=$(printf "$CLASSES" | awk -F '\t' '{print $1}' | rofi -dmenu -p "Pick a class" -i -format 'd')
CLASS_DIR=$(printf "$CLASSES" | sed -n "${CLASS}p" | awk '{print $2}')
NOTE=$(/bin/ls $CLASS_DIR | grep '.pdf' | rofi -dmenu -p "Pick a file" -i)

zathura $(echo "${CLASS_DIR}/$NOTE")
