#!/usr/bin/env bash
NOTES_DIR="$HOME/syncthing/notes/University"
CLASS_PATHS=$(find $NOTES_DIR -mindepth 3 -maxdepth 3 -type d)

CLASSES=""

for CLASS in $CLASS_PATHS 
do

  CLASSES=$(echo $CLASSES "$(basename $CLASS)")
done

CLASS=$(echo $CLASSES | rofi -dmenu -sep " ")


