#!/usr/bin/python3
"""
This script is a modified version of the script torrentcli (https://github.com/amogusussy/torrentCLI/blob/main/torrentcli)
it plays using peerflix which can be installed using `npm i -g peerflix`, args can be modified through the peerflix args constant
By default it uses the Libre Y instance found in the `TCLI_SOURCE` env variable, but if you need more instances the -s flag gives you a few
"""
import json
import subprocess
import os
import argparse
import random

import requests

PEERFLIX_ARGS = ["-v"]

class bg:
    PINK = "\033[95m"
    BLUE = "\033[94m"
    CYAN = "\033[96m"
    GREEN = "\033[92m"
    YELLOW = "\033[93m"
    RED = "\033[91m"
    NORM = "\033[0m"


def get_instances():
    instances = list()
    instances_json = requests.get(
        "https://raw.githubusercontent.com/Ahwxorg/LibreY/main/instances.json"
    ).content
    tmp = json.loads(instances_json)

    for i in tmp["instances"]:
        instances.append(i["clearnet"])

    return instances


def main():
    parser = argparse.ArgumentParser(description='A cli app to search and stream torrents, read the comment at the top of the file for more info')
    parser.add_argument('movie', type=str, nargs='*', help='Movie name')
    parser.add_argument('-m', '--magnet', action='store_true', help='Only print magnet link')
    parser.add_argument('-s', '--source', action='store_true', help='Choose Libre Y source')
    args = parser.parse_args()

    movie = " ".join(args.movie) if args.movie else input("Enter movie/show: ")
    search = movie.replace(" ", "%20")

    site =  os.environ['TCLI_SOURCE'] if 'TCLI_SOURCE' in os.environ else None
    if args.source or site is None:
        sites = get_instances()
        print("Choose source: ")
        for i, s in enumerate(sites):
            print(f"  {i}: {s}")
        site = sites[int(input("> "))]
    URL = f"{site}api.php?q={search}&p=0&t=3"
    data = requests.get(url=URL)
    data = data.json()

    numberOfOutputs = 8
    torrentStream = "peerflix"

    def output(a):
        for i in range(a):
            torrent = data[i]
            if torrent["seeders"] != 0:
                name = str(torrent["name"])
                seeders = str(torrent["seeders"])
                leechers = str(torrent["leechers"])
                size = str(torrent["size"])
                source = str(torrent["source"])
                print(
                    f"[{i + 1}]{bg.RED} {name} \n ---{bg.GREEN} [se] {seeders} {bg.PINK} [le] {leechers} {bg.BLUE} [size] {size} {bg.YELLOW} [src] {source} {bg.NORM}"
                )

    if len(data) < numberOfOutputs:
        a = len(data)
    else:
        a = numberOfOutputs
    output(a)

    try:
        x = int(input("Which torrent would you like? ")) - 1
    except ValueError:
        print("Please enter a number between 1 and ")

    if "1337x" in data[x]["source"]:
        re = str(f"{site}{data[x]['magnet'][1:]}")
        magnet = requests.get(re, allow_redirects=False).headers["location"]
    else:
        magnet = data[x]["magnet"]

    magnet = '"' + magnet + '"'
    command = " ".join([torrentStream, magnet] + PEERFLIX_ARGS)
    if args.magnet:
        print(magnet)
        exit()
    subprocess.run(command, shell=True)


try:
    main()
except KeyboardInterrupt:
    print("Exiting...")
