#!/usr/bin/env bash
new_folder="0"
if [[ $1 = "new" ]] then
    echo $1
    new_folder="1"
    selected=$(find ~/code ~/.config -mindepth 1 -maxdepth 3 -type d | fzf)
elif [[ $# -eq 1 ]]; then
    selected=$1
else
    selected=$(find ~/code ~/.config -mindepth 1 -maxdepth 3 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

if [[ $new_folder -eq "1" ]] then
  read -p "Enter folder name (no spaces): " folder_name
  selected="${selected}/${folder_name}"
  mkdir -p $selected
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

if [[ -z $tmux_running ]]; then
  tmux switch-client -t $selected_name
else
  tmux a -t $selected_name
fi
